### ISSUE TITLE
GUI - single flow speed

### ISSUE THREAD

**Issue by bostjanvihar** [IRNAS/new-harvest-rpi-drive-system#14]
- change ACW to CCW (correct from is "counter clock wise")
- CW and CCW are reversed
- when flow speed is set above 100% pwm, the values in the graph change accordingly, but the movement doesn't!

**Comment by NejcKle** [comment]
* Renamed ACW to CCW in 33d08aebfde88295cdc8a830b9107d804f35750b
* Reversed CW and CCW in 33b8a815266c30e21f069ef21f8de4c61ad5a839
* Capped the Flow speed setting in 07b68fafb03e3215e6b6d182692637d53e084d30
